### ISSUE TITLE
Cannot bump version 

### ISSUE THREAD

**Issue by rgreinho** [mbarkhau/pycalver#61] opened 2019-03-28 17:09 UTC
After fixing the issue #57, the example worked, but my real life project does not. I have the same error popping up again.

The project got cloned from [scrapd/datasets](https://github.com/scrapd/datasets).

### Repro steps

```bash
source venv/bin/activate
echo "Add a line to the readme" >> README.md
git commit -am save
pycalver bump
INFO    - fetching tags from remote (to turn off use: -n / --no-fetch)
INFO    - Working dir version        : 19.03.01.0
INFO    - Latest version from git tag: 19.03.24.0
INFO    - Old Version: 19.03.24.0
INFO    - New Version: 19.03.28.0
INFO    - git commit --file /var/folders/nc/5sdcykxd01x_pkjyh0dkvgpr0000gp/T/tmptz1_uhnc
Traceback (most recent call last):
  File "/Users/remygreinhofer/remy-project/datasets/venv/bin/pycalver", line 10, in <module>
    sys.exit(cli())
  File "/Users/remygreinhofer/remy-project/datasets/venv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/remygreinhofer/remy-project/datasets/venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/remygreinhofer/remy-project/datasets/venv/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/remygreinhofer/remy-project/datasets/venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/remygreinhofer/remy-project/datasets/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/remygreinhofer/remy-project/datasets/venv/lib/python3.7/site-packages/pycalver/__main__.py", line 291, in bump
    _bump(cfg, new_version, allow_dirty)
  File "/Users/remygreinhofer/remy-project/datasets/venv/lib/python3.7/site-packages/pycalver/__main__.py", line 216, in _bump
    _vcs.commit('bump version to {0}'.format(new_version))
  File "/Users/remygreinhofer/remy-project/datasets/venv/lib/python3.7/site-packages/pycalver/vcs.py", line 132, in commit
    self('commit', env=env, path=tmp_file.name)
  File "/Users/remygreinhofer/remy-project/datasets/venv/lib/python3.7/site-packages/pycalver/vcs.py", line 64, in __call__
    output_data = sp.check_output(cmd_str.split(), env=env, stderr=sp.
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'commit', '--file', '/var/folders/nc/5sdcykxd01x_pkjyh0dkvgpr0000gp/T/tmptz1_uhnc']' returned non-zero exit status 1.
```

### Environment

```bash
$ pycalver --version
pycalver, version v201903.0028
```
Related to #57

**Comment by mbarkhau** [comment] 2019-03-28 20:31
Thanks again for the bug report. I guess the first thing for me to do here is to expose the underlying issue by passing through the stderr of the failed command.

**Comment by mbarkhau** [comment] 2019-03-28 20:37
Looks like you don't have anything configured in your `[pycalver:file_patterns]` so `bump` doesn't change anything. Should be an easy fix to get a better error message.

**Comment by rgreinho** [comment] 2019-03-28 20:47
Oh that's correct, there is no file that I need to update. At least no file containing any version information. Most of the time only my data sets get updated and I bump the version to reflect that.

**Comment by mbarkhau** [comment] 2019-03-28 20:49
I suppose it would be reasonable to have an implicit pattern for the config file itself, since that's something every project will have and sometimes (as in your case) none other is needed.

**Comment by rgreinho** [comment] 2019-03-28 20:50
Not only. I package all my applications using PBR, and PBR uses the git tag to find the version. Maybe there should be a flag that I could use to indicate that I just want to tag but not edit any file?

As a workaround I could simply add a dummy file containing the version.

**Comment by mbarkhau** [comment] 2019-03-28 21:00
Atm. I think config file itself is the minimum that contains the version. 

```ini
[pycalver]
current_version = "19.03.01.0"
```

Maybe this is just a cutesy dogfooding thing that is not actually needed. When a project doesn't have any version tags (or indeed no VCS) this is what is used. Something to think about, but out of scope for this issue.

**Comment by rgreinho** [comment] 2019-03-29 00:32
So I updated the `[pycalver:file_patterns]` section my `setup.cfg` file as is:

```cfg
[pycalver]
current_version = "19.03.01.0"
version_pattern = "{yy}.{month}.{dom}.{PATCH}"
commit = True
tag = True
push = True

[pycalver:file_patterns]
setup.cfg =
    current_version = "{version}"
```

But now it compares the version to the `{pycalver}` format:

```
$ pycalver bump --patch
INFO    - fetching tags from remote (to turn off use: -n / --no-fetch)
INFO    - Working dir version        : 19.03.01.0
INFO    - Latest version from git tag: 19.03.24.0
INFO    - Old Version: 19.03.24.0
INFO    - New Version: 19.03.29.1
ERROR   - Invalid version string '19.03.29.1' for pattern '{pycalver}'/'(?P<pycalver>v(?P<year>\d{4})(?P<month>(?:0[0-9]|1[0-2]))\.(?P<bid>\d{4,})(?:-(?P<tag>(?:alpha|beta|dev|rc|post|final)))?)'
```

**Comment by mbarkhau** [comment] 2019-03-29 01:48
Yes I noticed this too while debugging. Should be fixed by 6d3dc6df and I just published a [beta release](https://pypi.org/project/pycalver/201903.29b0/) which includes fixes for both issues.
You can install it with `pip install pycalver==v201903.0029-beta`.

Thank you again for reporting issues and testing :100:.

**Comment by rgreinho** [comment] 2019-03-29 01:58
I can wait until you're done no worries. Unless you want me to help you test something.

Thanks a lot for being so responsive 🥇

**Comment by mbarkhau** [comment] 2019-03-29 20:42
Yes the idea was to do a bit of testing, but no problem. I just added some tests and am fairly confident things didn't get any worse, so I and uploaded [v201903.0030](https://pypi.org/project/pycalver/201903.30/).

I'm assuming the issue is fixed and am closing it for now.

**Closed by mbarkhau** 2019-03-29 20:42 UTC
